theme: jekyll-theme-minimal
logo: IMG_20200220_143932.jpg
title: Adeen Ayub
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD Scholar

  <a href="https://safe.lab.vcu.edu/people/">Security and Forensics Engineering Lab (SAFE) Lab</a>

  <a href="https://egr.vcu.edu/departments/computer/">Virginia Commonwealth University (VCU), USA </a>

  <a href="https://www.linkedin.com/in/adeenayub/">View My LinkedIn Profile</a> 
  
 
  Complete Resume <a https://raw.githubusercontent.com/adeenayub/Website-stuff/main/Adeen_Ayub_22.pdf?token=GHSAT0AAAAAABURGF5KFFVUOMLDTCDXYPCIYULQP3Q">here </a>
  
theme: jekyll-theme-minimal
